//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idl2cs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("idl2cs.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^/\*(?&lt;comment&gt;[^/]+)\*/.
        /// </summary>
        internal static string find_comment {
            get {
                return ResourceManager.GetString("find_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w*\s+enum\s+(?&lt;name1&gt;\w+)\s+{(?&lt;body&gt;[^}]+)}(?&lt;name2&gt;[^;]*);.
        /// </summary>
        internal static string find_enum {
            get {
                return ResourceManager.GetString("find_enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;func_type&gt;[\w+\s+]+)(?&lt;func_name&gt;\s+\w+)\s*\((?&lt;func_args&gt;[^\)]+)\)\s*;.
        /// </summary>
        internal static string find_function {
            get {
                return ResourceManager.GetString("find_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to helpstring\(\&quot;(?&lt;value&gt;[^\&quot;]+)\&quot;\).
        /// </summary>
        internal static string find_helpstring {
            get {
                return ResourceManager.GetString("find_helpstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \[(?&lt;attr&gt;[^\]]+)\]\s*interface\s+(?&lt;name&gt;[^:]+)\s*:\s*(?&lt;type&gt;[^{]+){(?&lt;function&gt;[^}]+)};.
        /// </summary>
        internal static string find_interface {
            get {
                return ResourceManager.GetString("find_interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typedef\s(?&lt;value&gt;[+\w+\s+]+)\s+(?&lt;key&gt;\w+);.
        /// </summary>
        internal static string find_typedef {
            get {
                return ResourceManager.GetString("find_typedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uuid\((?&lt;value&gt;[^\)]+)\).
        /// </summary>
        internal static string find_uuid {
            get {
                return ResourceManager.GetString("find_uuid", resourceCulture);
            }
        }
    }
}
